name: Environmennt Variables
env:
  WORKSPACE_ENV_VARIABLE: 'workspace env variable'
  OVER_RIDE: 'workflow'
on: [push]
jobs:
    ubuntu:
        env:
            JOB_ENV_VARIABLE: 'job env variable for ubuntu'
            OVER_RIDE: 'Job'
        runs-on: ubuntu-latest
        steps:
            - name: Print custom environment variables fromm ubuntu-latest
              env:
                STEP_ENV_VARIABLE: 'Step env variable from bash'
                OVER_RIDE: 'step'
              run: |
                echo "Access environment variables using shell syntax"
                echo "1. $WORKSPACE_ENV_VARIABLE"
                echo "2. $JOB_ENV_VARIABLE"
                echo "3. $STEP_ENV_VARIABLE"
                echo "4. $OVER_RIDE"
                echo ""
                echo "------------------------------"
                echo ""
                echo "Access environment variables using YAML syntax"
                echo "5. ${{ env.WORKSPACE_ENV_VARIABLE }}"
                echo "6. ${{ env.JOB_ENV_VARIABLE }}"
                echo "7. ${{ env.STEP_ENV_VARIABLE }}"
                echo "8. ${{ env.OVER_RIDE }}"
