name: keyword-releaser

on:
    push:
        branches:
            - main

jobs:
    buid:
        runs-on: ubuntu-latest
        steps:
            - uses: action/checkout@v3
            - uses: automate6500/keyword-release-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                args: 'FIXED'