# https://github.com/automate6500/python-web-app-cicd

name: Python Application Pipeline

on: 
    push:
        branches:
            - main

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Python environment
              uses: actions/setup-python@v4
            - name: Install requirements
              run: pip install --quiet --requirement requirements.txt
            - name: Lint code
              run: |
               flake8 --ignore=E501,E231 *.py
               pylint --disable=C0301 *.py
            - name: Run unit tests
              run: python -m unittest --verbose --failfast